### ISSUE TITLE
Investigate weird crash on login

### ISSUE THREAD

**Issue by MTRNord** [Nordgedanken/Morpheus#12]
Horrible Log I got:

```
marce@DESKTOP-EGVRLFQ MINGW64 ~/go/src/github.com/Nordgedanken/Morpheus/deploy/w                                                                                                                                                                                               indows (master)
$ ./Morpheus.exe
2017-10-10 17:52:23 - Starting Morpheus
2017-10-10 17:52:23 - Starting Auto Login Sequenze in background
2017-10-10 17:52:23 - msg=Failed to GET JSON to /_matrix/client/r0/rooms/!DgvjtO                                                                                                                                                                                               ljKujDBrxyHk:matrix.org/state/m.room.aliases code=404 wrapped=M_NOT_FOUND: Event                                                                                                                                                                                                not found.
2017-10-10 17:52:23 - msg=Failed to GET JSON to /_matrix/client/r0/rooms/!EDuQpg                                                                                                                                                                                               unAOTYiUKIcU:matrix.org/state/m.room.aliases code=404 wrapped=M_NOT_FOUND: Event                                                                                                                                                                                                not found.
2017-10-10 17:52:23 - msg=Failed to GET JSON to /_matrix/client/r0/rooms/!PisumN                                                                                                                                                                                               CACkTdCduGyB:matrix.org/state/m.room.aliases code=404 wrapped=M_NOT_FOUND: Event                                                                                                                                                                                                not found.
2017-10-10 17:52:23 - msg=Failed to GET JSON to /_matrix/client/r0/rooms/!OYyXUb                                                                                                                                                                                               cTKVsDBUniNn:matrix.eclabs.de/state/m.room.aliases code=404 wrapped=M_NOT_FOUND:                                                                                                                                                                                                Event not found.
2017-10-10 17:52:23 - msg=Failed to GET JSON to /_matrix/client/r0/rooms/!BPvgRc                                                                                                                                                                                               BVHzyFSlYkrg:matrix.org/state/m.room.aliases code=404 wrapped=M_NOT_FOUND: Event                                                                                                                                                                                                not found.
2017-10-10 17:52:23 - msg=Failed to GET JSON to /_matrix/client/r0/rooms/!zTIXGm                                                                                                                                                                                               DjyRcAqbrWab:matrix.ffslfl.net/state/m.room.aliases code=404 wrapped=M_NOT_FOUND                                                                                                                                                                                               : Event not found.
2017-10-10 17:52:23 - msg=Failed to GET JSON to /_matrix/client/r0/rooms/!cURbaf                                                                                                                                                                                               jkfsMDVwdRDQ:matrix.org/state/m.room.aliases code=404 wrapped=M_NOT_FOUND: Event                                                                                                                                                                                                not found.
2017-10-10 17:52:23 - msg=Failed to GET JSON to /_matrix/client/r0/rooms/!XqBunH                                                                                                                                                                                               wQIXUiqCaoxq:matrix.org/state/m.room.aliases code=404 wrapped=M_NOT_FOUND: Event                                                                                                                                                                                                not found.
2017-10-10 17:52:23 - msg=Failed to GET JSON to /_matrix/client/r0/rooms/!PQgcrP                                                                                                                                                                                               ZqvvbaAGKezi:matrix.org/state/m.room.aliases code=404 wrapped=M_NOT_FOUND: Event                                                                                                                                                                                                not found.
2017-10-10 17:52:23 - msg=Failed to GET JSON to /_matrix/client/r0/rooms/!fmweAI                                                                                                                                                                                               KpbYgSAtNnmw:matrix.ffslfl.net/state/m.room.aliases code=404 wrapped=M_NOT_FOUND                                                                                                                                                                                               : Event not found.
2017-10-10 17:52:23 - Syncing now
2017-10-10 17:52:23 - sync
2017-10-10 17:52:23 - Starting Logout Sequenze in background
Exception 0xc0000005 0x0 0xfffffffffffffff0 0x6fd08927
PC=0x6fd08927
signal arrived during external code execution

github.com/therecipe/qt/widgets._Cfunc_QWidget_KeyPressEventDefault(0x3875330, 0                                                                                                                                                                                               xd1c450)
        github.com/therecipe/qt/widgets/_obj/_cgo_gotypes.go:11080 +0x48
github.com/therecipe/qt/widgets.(*QWidget).KeyPressEventDefault.func1(0x3875330,                                                                                                                                                                                                0xd1c450)
        C:/Users/marce/go/src/github.com/therecipe/qt/widgets/widgets-minimal.go                                                                                                                                                                                               :12023 +0xaa
github.com/therecipe/qt/widgets.(*QWidget).KeyPressEventDefault(0xc042297a20, 0x                                                                                                                                                                                               a71c00, 0xc042152388)
        C:/Users/marce/go/src/github.com/therecipe/qt/widgets/widgets-minimal.go                                                                                                                                                                                               :12023 +0x77
main.NewMainUI.func6(0xc042152388)
        C:/Users/marce/go/src/github.com/Nordgedanken/Morpheus/uis.go:290 +0x277
github.com/therecipe/qt/widgets.callbackQWidget_KeyPressEvent(0x37d1a70, 0xd1c45                                                                                                                                                                                               0)
        C:/Users/marce/go/src/github.com/therecipe/qt/widgets/widgets-minimal.go                                                                                                                                                                                               :11988 +0x183
github.com/therecipe/qt/widgets._cgoexpwrap_5a494a80844b_callbackQWidget_KeyPres                                                                                                                                                                                               sEvent(0x37d1a70, 0xd1c450)
        github.com/therecipe/qt/widgets/_obj/_cgo_gotypes.go:14427 +0x3c
github.com/therecipe/qt/widgets._Cfunc_QApplication_QApplication_Exec(0x0)
        github.com/therecipe/qt/widgets/_obj/_cgo_gotypes.go:1138 +0x50
github.com/therecipe/qt/widgets.QApplication_Exec(0xc0420ddaf0)
        C:/Users/marce/go/src/github.com/therecipe/qt/widgets/widgets-minimal.go                                                                                                                                                                                               :1169 +0x29
main.main()
        C:/Users/marce/go/src/github.com/Nordgedanken/Morpheus/main.go:95 +0x67e

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        C:/Go/src/runtime/asm_amd64.s:2197 +0x1

goroutine 5 [chan receive]:
github.com/tidwall/buntdb.(*DB).backgroundManager(0xc042014a00)
        C:/Users/marce/go/src/github.com/tidwall/buntdb/buntdb.go:542 +0xeb
created by github.com/tidwall/buntdb.Open
        C:/Users/marce/go/src/github.com/tidwall/buntdb/buntdb.go:165 +0x20d

goroutine 53 [IO wait]:
net.runtime_pollWait(0x7140f00, 0x72, 0xa6c1d0)
        C:/Go/src/runtime/netpoll.go:164 +0x60
net.(*pollDesc).wait(0xc0421a81a0, 0x72, 0xa6c1d0, 0x0)
        C:/Go/src/net/fd_poll_runtime.go:75 +0x3f
net.(*ioSrv).ExecIO(0xc0421a6000, 0xc0421a8060, 0x7d4dae, 0x7, 0x7e86e0, 0x0, 0x                                                                                                                                                                                               64, 0x1)
        C:/Go/src/net/fd_windows.go:196 +0xfe
net.(*netFD).Read(0xc0421a8000, 0xc04212ec00, 0x400, 0x400, 0x0, 0x0, 0x0)
        C:/Go/src/net/fd_windows.go:452 +0x13d
net.(*conn).Read(0xc0421a6010, 0xc04212ec00, 0x400, 0x400, 0x0, 0x0, 0x0)
        C:/Go/src/net/net.go:181 +0x77
crypto/tls.(*block).readFromUntil(0xc04219a1b0, 0x7140fc0, 0xc0421a6010, 0x5, 0x                                                                                                                                                                                               c0421a6010, 0x28)
        C:/Go/src/crypto/tls/conn.go:488 +0x9f
crypto/tls.(*Conn).readRecord(0xc0421ac000, 0x7e8d17, 0xc0421ac120, 0x452b80)
        C:/Go/src/crypto/tls/conn.go:590 +0xcb
crypto/tls.(*Conn).Read(0xc0421ac000, 0xc0421bf000, 0x1000, 0x1000, 0x0, 0x0, 0x                                                                                                                                                                                               0)
        C:/Go/src/crypto/tls/conn.go:1134 +0x124
net/http.(*persistConn).Read(0xc042194000, 0xc0421bf000, 0x1000, 0x1000, 0x5, 0x                                                                                                                                                                                               450ad0, 0xc04218a180)
        C:/Go/src/net/http/transport.go:1316 +0x152
bufio.(*Reader).fill(0xc0421a0ba0)
        C:/Go/src/bufio/bufio.go:97 +0x11e
bufio.(*Reader).Peek(0xc0421a0ba0, 0x1, 0xc042139be5, 0xc042297a01, 0x4, 0xc0420                                                                                                                                                                                               1a300, 0x0)
        C:/Go/src/bufio/bufio.go:129 +0x6e
net/http.(*persistConn).readLoop(0xc042194000)
        C:/Go/src/net/http/transport.go:1474 +0x19d
created by net/http.(*Transport).dialConn
        C:/Go/src/net/http/transport.go:1117 +0xa3c

goroutine 54 [select]:
net/http.(*persistConn).writeLoop(0xc042194000)
        C:/Go/src/net/http/transport.go:1704 +0x441
created by net/http.(*Transport).dialConn
        C:/Go/src/net/http/transport.go:1118 +0xa61

goroutine 8 [select]:
net/http.(*persistConn).roundTrip(0xc042194000, 0xc042198240, 0x0, 0x0, 0x0)
        C:/Go/src/net/http/transport.go:1898 +0x97b
net/http.(*Transport).RoundTrip(0xa9af00, 0xc042282100, 0xa9af00, 0x0, 0x0)
        C:/Go/src/net/http/transport.go:391 +0x753
net/http.send(0xc042282100, 0xa6e280, 0xa9af00, 0x0, 0x0, 0x0, 0x0, 0x8, 0xc0421                                                                                                                                                                                               52110, 0x410f4f)
        C:/Go/src/net/http/client.go:249 +0x169
net/http.(*Client).send(0xad5be0, 0xc042282100, 0x0, 0x0, 0x0, 0xc042152110, 0x0                                                                                                                                                                                               , 0x1, 0x409f15)
        C:/Go/src/net/http/client.go:173 +0x10f
net/http.(*Client).Do(0xad5be0, 0xc042282100, 0xc, 0x7d9ac3, 0x10)
        C:/Go/src/net/http/client.go:595 +0x25b
github.com/matrix-org/gomatrix.(*Client).MakeRequest(0xc04213e080, 0x7d27c4, 0x3                                                                                                                                                                                               , 0xc0421829a0, 0x15a, 0x0, 0x0, 0x726760, 0xc0421520f0, 0x0, ...)
        C:/Users/marce/go/src/github.com/matrix-org/gomatrix/client.go:204 +0x21                                                                                                                                                                                               d
github.com/matrix-org/gomatrix.(*Client).SyncRequest(0xc04213e080, 0x7530, 0x0,                                                                                                                                                                                                0x0, 0xc042297ae8, 0x3, 0x0, 0x0, 0x0, 0xc042012620, ...)
        C:/Users/marce/go/src/github.com/matrix-org/gomatrix/client.go:270 +0x21                                                                                                                                                                                               b
github.com/matrix-org/gomatrix.(*Client).Sync(0xc04213e080, 0xc04211dfb8, 0x1)
        C:/Users/marce/go/src/github.com/matrix-org/gomatrix/client.go:132 +0x13                                                                                                                                                                                               d
main.NewMainUI.func5(0xc04213e080)
        C:/Users/marce/go/src/github.com/Nordgedanken/Morpheus/uis.go:269 +0xc8
created by main.NewMainUI
        C:/Users/marce/go/src/github.com/Nordgedanken/Morpheus/uis.go:276 +0xc46

goroutine 10 [IO wait]:
net.runtime_pollWait(0x7140e40, 0x72, 0xa6c1d0)
        C:/Go/src/runtime/netpoll.go:164 +0x60
net.(*pollDesc).wait(0xc0422e01a0, 0x72, 0xa6c1d0, 0x0)
        C:/Go/src/net/fd_poll_runtime.go:75 +0x3f
net.(*ioSrv).ExecIO(0xc0421a6000, 0xc0422e0060, 0x7d4dae, 0x7, 0x7e86e0, 0x0, 0x                                                                                                                                                                                               64, 0x1)
        C:/Go/src/net/fd_windows.go:196 +0xfe
net.(*netFD).Read(0xc0422e0000, 0xc04212f400, 0x400, 0x400, 0x0, 0x0, 0x0)
        C:/Go/src/net/fd_windows.go:452 +0x13d
net.(*conn).Read(0xc042004030, 0xc04212f400, 0x400, 0x400, 0x0, 0x0, 0x0)
        C:/Go/src/net/net.go:181 +0x77
crypto/tls.(*block).readFromUntil(0xc0421405a0, 0x7140fc0, 0xc042004030, 0x5, 0x                                                                                                                                                                                               c042004030, 0x28)
        C:/Go/src/crypto/tls/conn.go:488 +0x9f
crypto/tls.(*Conn).readRecord(0xc0421ac700, 0x7e8d17, 0xc0421ac820, 0x452b80)
        C:/Go/src/crypto/tls/conn.go:590 +0xcb
crypto/tls.(*Conn).Read(0xc0421ac700, 0xc0422eb000, 0x1000, 0x1000, 0x0, 0x0, 0x                                                                                                                                                                                               0)
        C:/Go/src/crypto/tls/conn.go:1134 +0x124
net/http.(*persistConn).Read(0xc0421e4000, 0xc0422eb000, 0x1000, 0x1000, 0x5, 0x                                                                                                                                                                                               450ad0, 0xc0420d4c00)
        C:/Go/src/net/http/transport.go:1316 +0x152
bufio.(*Reader).fill(0xc0420d4a80)
        C:/Go/src/bufio/bufio.go:97 +0x11e
bufio.(*Reader).Peek(0xc0420d4a80, 0x1, 0xc042463be5, 0xc0422da101, 0x4, 0xc0420                                                                                                                                                                                               d4ae0, 0x0)
        C:/Go/src/bufio/bufio.go:129 +0x6e
net/http.(*persistConn).readLoop(0xc0421e4000)
        C:/Go/src/net/http/transport.go:1474 +0x19d
created by net/http.(*Transport).dialConn
        C:/Go/src/net/http/transport.go:1117 +0xa3c

goroutine 11 [select]:
net/http.(*persistConn).writeLoop(0xc0421e4000)
        C:/Go/src/net/http/transport.go:1704 +0x441
created by net/http.(*Transport).dialConn
        C:/Go/src/net/http/transport.go:1118 +0xa61
rax     0x0
rbx     0x3875330
rcx     0x3875330
rdi     0xab8ac0
rsi     0x0
rbp     0xab9390
rsp     0xd1b940
r8      0xab8ac0
r9      0x0
r10     0xc042152388
r11     0xc042152388
r12     0x1
r13     0x72
r14     0x388
r15     0x400
rip     0x6fd08927
rflags  0x10202
cs      0x33
fs      0x53
gs      0x2b
```

**Comment by MTRNord** [comment]
Somehow the DB failed on Logout. Now the client is in a deadlock state
